### ISSUE TITLE
Can't start app using posted instructions

### ISSUE THREAD

**Issue by jabbett** [andreioprisan/meteor-newrelic#4]
Here's my start-up command:

``` sh
#! /bin/bash
NEW_RELIC_NO_CONFIG_FILE=TRUE;NEW_RELIC_LICENSE_KEY=<not_shown>;NEW_RELIC_APP_NAME=rdmppr;NEW_RELIC_LOG_LEVEL=debug;ROOT_URL=http://localhost.meteor.com meteor --settings settings.json
```

I get this error:

```
W20140312-10:11:57.016(-4)? (STDERR) /Users/jabbett/.meteor/tools/f3947a4651/lib/node_modules/fibers/future.js:173
W20140312-10:11:57.016(-4)? (STDERR)                        throw(ex);
W20140312-10:11:57.017(-4)? (STDERR)                              ^
W20140312-10:11:57.017(-4)? (STDERR) Error: Unable to find New Relic module configuration. A default
W20140312-10:11:57.018(-4)? (STDERR) configuration file can be copied from /Users/jabbett/.meteorite/packages/meteor-newrelic/andreioprisan/meteor-newrelic/54131ffaa2f47533339959bd296557ccb692e314/.build/npm/node_modules/newrelic/lib/config.default.js
W20140312-10:11:57.018(-4)? (STDERR) and put at /Users/jabbett/Workspace/rdmppr/.meteor/local/build/programs/server/newrelic.js or
W20140312-10:11:57.019(-4)? (STDERR) /Users/jabbett/Workspace/rdmppr/.meteor/local/build/newrelic.js.
W20140312-10:11:57.019(-4)? (STDERR)     at _failHard (/Users/jabbett/.meteorite/packages/meteor-newrelic/andreioprisan/meteor-newrelic/54131ffaa2f47533339959bd296557ccb692e314/.build/npm/node_modules/newrelic/lib/config.js:154:9)
W20140312-10:11:57.019(-4)? (STDERR)     at Function.initialize (/Users/jabbett/.meteorite/packages/meteor-newrelic/andreioprisan/meteor-newrelic/54131ffaa2f47533339959bd296557ccb692e314/.build/npm/node_modules/newrelic/lib/config.js:604:25)
W20140312-10:11:57.019(-4)? (STDERR)     at Object.<anonymous> (/Users/jabbett/.meteorite/packages/meteor-newrelic/andreioprisan/meteor-newrelic/54131ffaa2f47533339959bd296557ccb692e314/.build/npm/node_modules/newrelic/lib/logger.js:49:46)
W20140312-10:11:57.019(-4)? (STDERR)     at Module._compile (module.js:456:26)
W20140312-10:11:57.020(-4)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20140312-10:11:57.020(-4)? (STDERR)     at Module.load (module.js:356:32)
W20140312-10:11:57.020(-4)? (STDERR)     at Function.Module._load (module.js:312:12)
W20140312-10:11:57.020(-4)? (STDERR)     at Module.require (module.js:364:17)
W20140312-10:11:57.020(-4)? (STDERR)     at require (module.js:380:17)
W20140312-10:11:57.020(-4)? (STDERR)     at Object.<anonymous> (/Users/jabbett/.meteorite/packages/meteor-newrelic/andreioprisan/meteor-newrelic/54131ffaa2f47533339959bd296557ccb692e314/.build/npm/node_modules/newrelic/index.js:4:15)
=> Exited with code: 8
```

I tried following the instructions in the error message, but every time I copy `newrelic.js` into `.meteor/local/build/programs/server/`, the file disappears.

**Comment by andreioprisan** [comment]
Since meteor package APIs do not allow for changing internal configs for packages, you must use external config variables.

**Comment by andreioprisan** [comment]
Config options are in the readme.

**Comment by jabbett** [comment]
Yes, I did use the external variables, as you can see in my bash script.
(I only tried using the file because it didn't work with the readme's instructions.)

**Comment by jabbett** [comment]
With some help from nearby shell-savvy colleagues, I updated my bash script to this, and it seems to work:

``` sh
#!/bin/bash
(export NEW_RELIC_NO_CONFIG_FILE=TRUE;export NEW_RELIC_LICENSE_KEY=BLERG;export NEW_RELIC_APP_NAME=rdmppr;export NEW_RELIC_LOG_LEVEL=debug;export ROOT_URL=http://localhost.meteor.com;meteor --settings settings.json)
```

I hope this helps others that aren't as familiar with setting environment variables on the command line.

**Comment by mingderwang** [comment]
Thanks @jabbett, it works.

**Comment by fgm** [comment]
@jabbett You seem to be one of the few who say "it works" with regard to NewRelic on Meteor. I have a similar configuration and only get the memory usage in my NR app report: did you manage to get something else ? NR keeps complaining that connect and mongodb were loaded prior to its agent.

**Comment by jabbett** [comment]
@FGM Sorry, it's been 2.5 years since I dabbled with Meteor and New Relic.

**Comment by fgm** [comment]
Thanks, I finally got it working to some extent (native-metrics). Working on getting more, especially now that Kadira is going down.

**Comment by fIa5h** [comment]
@FGM do you have a codebase you can share to help me get a better understanding for how you've achieved this? Are you using meteor-up?

Many thanks~

**Comment by fgm** [comment]
@RyanThomasMusser I just finished by adding custom code to the standard NewRelic package. Regrettably, the customer did not agree to open source it for now. In short, what I did create is:

* a NrMethod class and NrMethods instance monkey-patching Meteor.methods as a side effect of importing our package
* a createTracer() function allowing the capture of background transactions
* a NrBackgroundTask to allow a simple way to create background transactions

Native metrics, Connect, Express, MongoDB, are captured normally with that setup, using the newrelic and native-metrics packages. We still have the warning on top of the NewRelic screens, but the metrics are there, including those at the "node vm" level.

**Comment by fIa5h** [comment]
@FGM Wonderful - your response is very helpful. Thank you, I appreciate it!

**Comment by GeoffreyBooth** [comment]
@fgm and @RyanThomasMusser and @jabbett, thanks for sharing what you have above. I’m also working on trying to integrate New Relic with a Meteor app. I’m building my app in Docker, using a Dockerfile based on this: https://github.com/disney/meteor-base/blob/master/example/default.dockerfile. Since it starts the app via `node main.js`, I added some lines to my build script to prepend `require('newrelic');` to the start of `main.js`, and set the environment variables. This gets the most basic parts of New Relic working; I see the app send some data, such as stats about static asset transactions (client loading of fonts, etc.), but little else.

Any advice on how to get more instrumentation than this? In particular I want to see stats about calls to Mongo, which I think should be supported out-of-the-box by New Relic since somewhere down far under the hood of Meteor I’m sure Meteor is just using the official Mongo package. My hunch is that this is probably happening in a different fiber than wherever `main.js` is loaded, and I need to do some work to get New Relic loaded over there. (Perhaps using some of the steps described in https://docs.newrelic.com/docs/agents/nodejs-agent/supported-features/nodejs-custom-instrumentation?) I’ve found various Atmosphere packages for loading New Relic, but they all appear to be using a very out-of-date New Relic client. I’ve applied the `cls-fibers` patch per https://github.com/oskarszoon/meteor-newrelic/blob/master/lib/server.js and https://discuss.newrelic.com/t/feature-idea-meteor-js-support/27595/14.

Any suggestions would be most appreciated!

**Comment by fgm** [comment]
Actually, we continued work on instrumentation, combining the open source Kadira for traces with an enhanced version of MeteorServerInfo piped to Grafana, which I was allowed to open source: https://github.com/fgm/meteor_server_info and the next step coming these days is actually removing NewRelic as it does not bring sufficient additional value for our needs now that we have this combination of general metrics from MeteorServerInfo and traces from Kadira.
We actually used Elastic APM for some time but found it more valuable to use this specific combination instead.
